sudo: required

dist: trusty

before_install: 
  - if [ $TRAVIS_OS_NAME == "linux" ]; then 
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - wget -O os.deb http://oscript.io/downloads/night-build/deb
  - sudo apt-get install mono-complete mono-devel
  - sudo dpkg -i os.deb; sudo apt install -f
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install opm
  - oscript

install: 
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os install
  - sudo oscript /usr/share/oscript/lib/opm/src/opm.os -l 1testrunner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - oscript ./oscript_library/bin/1testrunner.sh -runall tests
